class Bonus {
  final String hotel,
      operator,
      room,
      name,
      surname,
      voucherDate,
      checkIn,
      checkOut,
      status,
      agency;
  final int usedBonus;

  Bonus(
      {this.hotel = '',
      this.agency = '',
      this.room = '',
      this.operator = '',
      this.name = '',
      this.surname = '',
      this.voucherDate = '',
      this.checkIn = '',
      this.checkOut = '',
      this.status = 'completed',
      this.usedBonus = 0});
}

List bonusRequests = [
  Bonus(
    hotel: "NG Phaselis Bay",
    agency: "PENUSULA",
    room: "SKS",
    name: "Hakan",
    surname: "Ötmez",
    voucherDate: "12.12.20022",
    checkIn: "12/12/2022",
    status: "Requested",
    checkOut: "15/12/2022",
  ),
  Bonus(
    hotel: "NG Phaselis Bay",
    agency: "PENUSULA",
    room: "Nakit",
    name: "Hakan",
    surname: "Ötmez",
    voucherDate: "12.12.20022",
    checkIn: "12/12/2022",
    status: "Requested",
    checkOut: "15/12/2022",
  ),
  Bonus(
    hotel: "NG Phaselis Bay",
    agency: "PENUSULA",
    room: "SKS",
    name: "Caner",
    surname: "Sönmez",
    voucherDate: "12.12.20022",
    checkIn: "12/12/2022",
    status: "Requested",
    checkOut: "15/12/2022",
  ),
  Bonus(
    hotel: "NG Phaselis Bay",
    agency: "PENUSULA",
    room: "Nakit",
    name: "Hakan",
    surname: "Ötmez",
    voucherDate: "12.12.20022",
    checkIn: "12/12/2022",
    status: "Requested",
    checkOut: "15/12/2022",
  ),
];

List bonusCompleted = [
  Bonus(
      hotel: "NG Phaselis Bay",
      agency: "PENUSULA",
      room: "SKS",
      name: "Hakan",
      surname: "Ötmez",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      checkOut: "15/12/2022",
      status: "Completed",
      usedBonus: 986),
  Bonus(
      hotel: "NG Phaselis Bay",
      agency: "PENUSULA",
      room: "SKS",
      name: "Hakan",
      surname: "Ötmez",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      checkOut: "15/12/2022",
      status: "Completed",
      usedBonus: 986),
];

List bonusPreConfirmed = [
  Bonus(
      hotel: "NG Phaselis Bay",
      agency: "PENUSULA",
      room: "SKS",
      name: "Hakan",
      surname: "Ötmez",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      checkOut: "15/12/2022",
      status: "Confirmed",
      usedBonus: 986),
  Bonus(
      hotel: "NG Phaselis Bay",
      agency: "PENUSULA",
      room: "SKS",
      name: "Hakan",
      surname: "Ötmez",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      checkOut: "15/12/2022",
      status: "Confirmed",
      usedBonus: 986),
  Bonus(
      hotel: "NG Phaselis Bay",
      agency: "PENUSULA",
      room: "SKS",
      name: "Hakan",
      surname: "Ötmez",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      status: "Confirmed",
      checkOut: "15/12/2022",
      usedBonus: 986),
  Bonus(
      hotel: "NG Phaselis Bay",
      agency: "PENUSULA",
      room: "SKS",
      name: "Hakan",
      surname: "Ötmez",
      voucherDate: "12.12.20022",
      status: "Confirmed",
      checkIn: "12/12/2022",
      checkOut: "15/12/2022",
      usedBonus: 986),
];

List bonusCancelled = [
  Bonus(
      hotel: "NG Phaselis Bay",
      agency: "PENUSULA",
      room: "SKS",
      name: "Hakan",
      surname: "Ötmez",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      status: "Cancelled",
      checkOut: "15/12/2022",
      usedBonus: 986),
];
