class Reservations {
  final String agency,
      recordUser,
      hotel,
      operator,
      guestName,
      guestSurname,
      nationality,
      voucher,
      room,
      voucherDate,
      checkIn,
      status,
      checkOut;

  final int overnight, totalBonus;
  final double sum;

  Reservations(
      {this.agency = '',
      this.recordUser = '',
      this.hotel = '',
      this.guestSurname = '',
      this.operator = '',
      this.guestName = '',
      this.nationality = '',
      this.voucher = '',
      this.room = '',
      this.voucherDate = '',
      this.checkIn = '',
      this.checkOut = '',
      this.overnight = 0,
      this.totalBonus = 0,
      this.sum = 0,
      this.status = 'completed'});
}

List completed = [
  Reservations(
      hotel: "NG Phaselis Bay",
      recordUser: "Ayhan Sicim",
      agency: "Penusula",
      operator: "ETS",
      guestName: "Hakan",
      guestSurname: "Ötmez",
      nationality: "EN",
      voucher: "0039585",
      room: "STK",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      status: "Completed",
      checkOut: "15/12/2022",
      sum: 0.0,
      overnight: 2),
  Reservations(
      hotel: "NG Phaselis Bay",
      recordUser: "Bülent Şen",
      agency: "Penusula",
      operator: "ETS",
      guestName: "Ayşe",
      guestSurname: "Dönmez",
      nationality: "ABD",
      voucher: "0039585",
      room: "STK",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      status: "Completed",
      checkOut: "15/12/2022",
      sum: 0.0,
      overnight: 2),
];

List preConfirmed = [
  Reservations(
      hotel: "NG Phaselis Bay",
      recordUser: "Bülent Şen",
      agency: "Penusula",
      operator: "SUNFUN",
      guestName: "Emre",
      guestSurname: "Kaymaz",
      nationality: "TR",
      voucher: "0039585",
      room: "STK",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      status: "Confirmed",
      checkOut: "15/12/2022",
      sum: 0.0,
      overnight: 3),
  Reservations(
      hotel: "NG Phaselis Bay",
      recordUser: "Ayhan Sicim",
      agency: "Penusula",
      operator: "TUI",
      guestName: "Mehtap",
      guestSurname: "Akar",
      nationality: "KZS",
      voucher: "0039585",
      room: "STK",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      status: "Confirmed",
      checkOut: "15/12/2022",
      sum: 0.0,
      overnight: 5),
];

List cancelled = [
  Reservations(
      hotel: "NG Phaselis Bay",
      recordUser: "Bülent Şen",
      agency: "Penusula",
      operator: "ETS",
      guestName: "Mustafa",
      guestSurname: "ŞemYılmaz",
      nationality: "EN",
      voucher: "0039585",
      room: "STK",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      status: "Cancelled",
      checkOut: "15/12/2022",
      sum: 0.0,
      overnight: 1),
  Reservations(
      hotel: "NG Phaselis Bay",
      recordUser: "Ayhan Sicim",
      agency: "Penusula",
      operator: "Odeon",
      guestName: "Fatma",
      guestSurname: "Dönmez",
      nationality: "ABD",
      voucher: "0039585",
      room: "STK",
      voucherDate: "12.12.20022",
      checkIn: "12/12/2022",
      status: "Cancelled",
      checkOut: "15/12/2022",
      sum: 0.0,
      overnight: 2),
];
