class User {
  final String operator,
      name,
      surname,
      email,
      country,
      city,
      status,
      registerDate,
      kvkk,
      agency;

  User(
      {this.email = '',
      this.agency = '',
      this.city = '',
      this.operator = '',
      this.name = '',
      this.surname = '',
      this.country = '',
      this.registerDate = '',
      this.kvkk = '',
      this.status = 'completed'});
}

List userRequests = [
  User(
    country: "Rusya",
    agency: "PENUSULA",
    city: "Ankara",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    email: "emre@mail.com",
    status: "Requested",
    kvkk: "Onaylı",
  ),
  User(
    country: "Türkiye",
    agency: "PENUSULA",
    city: "İstanbul",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    email: "hakan@mail.com",
    status: "Requested",
    kvkk: "Onaylı",
  ),
  User(
    country: "Türkiye",
    agency: "PENUSULA",
    city: "Ankara",
    name: "Caner",
    surname: "Sönmez",
    registerDate: "12.12.20022",
    email: "caner@mail.com",
    status: "Requested",
    kvkk: "Onaylı",
  ),
  User(
    country: "Türkiye",
    agency: "PENUSULA",
    city: "İstanbul",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    email: "mail@mail.com",
    status: "Requested",
    kvkk: "Onaylı",
  ),
];

List userDenied = [
  User(
    country: "Türkiye",
    agency: "PENUSULA",
    city: "Ankara",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    email: "mail@mail.com",
    kvkk: "Onaylı",
    status: "Denied",
  ),
  User(
    country: "Türkiye",
    agency: "PENUSULA",
    city: "Ankara",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    email: "mail@mail.com",
    kvkk: "Onaylı",
    status: "Denied",
  ),
];

List userConfirmed = [
  User(
    country: "Türkiye",
    agency: "PENUSULA",
    city: "Ankara",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    email: "mail@mail.com",
    kvkk: "Onaylı",
    status: "Confirmed",
  ),
  User(
    country: "Türkiye",
    agency: "PENUSULA",
    city: "Ankara",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    email: "mail@mail.com",
    kvkk: "Onaylı",
    status: "Confirmed",
  ),
  User(
    country: "Türkiye",
    agency: "ODEON",
    city: "Ankara",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    email: "mail@mail.com",
    status: "Confirmed",
    kvkk: "Onaylı",
  ),
  User(
    country: "Türkiye",
    agency: "PENUSULA",
    city: "Ankara",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    status: "Confirmed",
    email: "mail@mail.com",
    kvkk: "Onaylı",
  ),
];

List userBlackList = [
  User(
    country: "Türkiye",
    agency: "PENUSULA",
    city: "Ankara",
    name: "Hakan",
    surname: "Ötmez",
    registerDate: "12.12.20022",
    email: "mail@mail.com",
    status: "BlackList",
    kvkk: "Onaylı",
  ),
];
